name: PluginControl
version: '${version}'
main: com.armamc.plugincontrol.PluginControl
api-version: 1.13
authors: [ ThiagoROX ]
description: Plugin to check if all important plugins have been successfully loaded.
website: https://armnamc.com
commands:
  plugincontrol:
    description: "Command to manage PluginControl"
    usage: "/<command> <add|remove|action|kick-message|toggle|on|off|list|reload>"
    aliases: [pc, plcontrol]
    permission: plugincontrol.use
    permission-message: "You do not have permission to use this command"