name: PluginControl
version: '${version}'
main: com.armamc.plugincontrol.PluginControl
api-version: 1.13
authors: [ ThiagoROX ]
description: Plugin to check if all important plugins have been successfully loaded.
website: https://github.com/SrBedrock/PluginControl
libraries:
  - "net.kyori:adventure-api:4.14.0"
  - "net.kyori:adventure-platform-bukkit:4.3.0"
  - "net.kyori:adventure-text-minimessage:4.14.0"
  - "net.kyori:adventure-text-serializer-legacy:4.14.0"

commands:
  plugincontrol:
    description: "Command to manage PluginControl"
    usage: "/<command> <add|remove|action|kick-message|toggle|on|off|list|reload>"
    aliases: [pc, plcontrol]
    permission: plugincontrol.use
    permission-message: "You do not have permission to use this command"