name: PluginControl
version: '${version}'
main: com.armamc.plugincontrol.PluginControl
api-version: '1.13'
authors: [ ThiagoROX ]
description: This minecraft plugin allows you to define which plugin has to be successfully enabled after server startup.
website: https://github.com/SrBedrock/PluginControl
libraries:
  - "net.kyori:adventure-api:4.14.0"
  - "net.kyori:adventure-platform-bukkit:4.3.0"
  - "net.kyori:adventure-text-minimessage:4.14.0"
  - "net.kyori:adventure-text-serializer-legacy:4.14.0"

commands:
  plugincontrol:
    description: "Command to manage PluginControl"
    usage: "/<command> <add|remove|check|group|action|kick-message|toggle|enable|disable|list|reload|help>"
    aliases: [ pc, plcontrol ]
    permission: plugincontrol.use

permissions:
  plugincontrol.use:
    description: "Allow using PluginControl commands"
    default: op
  plugincontrol.notify:
    description: "Allow seeing the notification when a plugin is not loaded or enabled"
    default: op
  plugincontrol.bypass:
    description: "Bypass block when a plugin is not loaded or enabled"
    default: false
