[versions]
java = "21"

# plugins
shadow = "9.6.1"
run-paper = "3.1.0"
velocity = "3.4.0-SNAPSHOT"
bungeecord = "1.21-R0.4"

# libs
updatechecker = "v2.5.1"
spigot = "26.2-R0.1-SNAPSHOT"
adventure-api = "5.2.0"
adventure-platform-bukkit = "4.4.1"
h2 = "2.5.250"
mysql = "26.7.0"
sqlite = "3.53.4.0"
hikari = "7.1.0"

[libraries]
updatecheckerjava = { module = "com.github.TechnicJelle:UpdateCheckerJava", version.ref = "updatechecker" }

spigot-api = { module = "org.spigotmc:spigot-api", version.ref = "spigot" }

adventure-api = { module = "net.kyori:adventure-api", version.ref = "adventure-api" }
adventure-minimessage = { module = "net.kyori:adventure-text-minimessage", version.ref = "adventure-api" }
adventure-serializer-legacy = { module = "net.kyori:adventure-text-serializer-legacy", version.ref = "adventure-api" }
adventure-platform-bukkit = { module = "net.kyori:adventure-platform-bukkit", version.ref = "adventure-platform-bukkit" }
h2 = { module = "com.h2database:h2", version.ref = "h2" }
mysql = { module = "com.mysql:mysql-connector-j", version.ref = "mysql" }
sqlite = { module = "org.xerial:sqlite-jdbc", version.ref = "sqlite" }
hikari = { module = "com.zaxxer:HikariCP", version.ref = "hikari" }
velocity-api = { module = "com.velocitypowered:velocity-api", version.ref = "velocity" }
bungeecord-api = { module = "net.md-5:bungeecord-api", version.ref = "bungeecord" }

[bundles]
adventure = [
    "adventure-api",
    "adventure-minimessage",
    "adventure-serializer-legacy",
    "adventure-platform-bukkit"
]

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
run-paper = { id = "xyz.jpenilla.run-paper", version.ref = "run-paper" }
