update-notifier: false
enabled: false
storage:
  # yaml, h2, sqlite or mysql
  type: yaml
  database:
    file: data.db
    pool-size: 5
    host: localhost
    port: 3306
    name: plugincontrol
    username: root
    password: ""
    use-ssl: true
    require-ssl: true
    verify-server-certificate: true
# Action to take if all listed plugins are not enabled.
# log-to-console
# disallow-player-login
# shutdown-server
action: log-to-console
