name: "Build"

on:
  push:
    branches: [ 'main', 'dev' ]
    paths:
      - 'gradle/**'
      - 'src/**'
      - 'build.gradle.kts'
      - 'settings.gradle.kts'
      - 'gradlew'
      - 'gradlew.bat'
  pull_request:
    branches: [ 'main', 'dev' ]
    paths:
      - 'gradle/**'
      - 'src/**'
      - 'build.gradle.kts'
      - 'settings.gradle.kts'
      - 'gradlew'
      - 'gradlew.bat'
  workflow_dispatch:
permissions:
  contents: read

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          check-latest: true
      - name: Run chmod to make gradlew executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v3.5.0
        with:
          arguments: build
      - name: Upload Plugin
        uses: actions/upload-artifact@v4.3.4
        with:
          name: PluginControl
          path: build/libs/*.jar